# Generated by Django 2.2.7 on 2019-12-18 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191217_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordreset',
            options={'ordering': ['-created_at'], 'verbose_name': 'nova senha', 'verbose_name_plural': 'Novas senhas'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='confirmed',
            field=models.BooleanField(blank=True, default=False, verbose_name='confirmado?'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='key',
            field=models.CharField(max_length=100, unique=True, verbose_name='chave'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resets', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
